package com.example.android.unscramble.ui.game
const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20
val allWordsList: List<String> =
    listOf("hewan",
        "mobil",
        "anekdot",
        "alfabet",
        "semua",
        "keren",
        "muncul",
        "balon",
        "keranjang",
        "bangku",
        "terbaik",
        "ulang tahun",
        "buku",
        "tas kerja",
        "kamera",
        "berkemah",
        "lilin",
        "kucing",
        "kembang kol",
        "obrolan",
        "anak-anak",
        "kelas",
        "klasik",
        "ruang kelas",
        "kopi",
        "berwarna-warni",
        "kue kering",
        "kreatif",
        "pelayaran",
        "menari",
        "siang hari",
        "dinosaurus",
        "gagang pintu",
        "makan",
        "mimpi",
        "senja",
        "makan",
        "gajah",
        "zamrud",
        "menyeramkan",
        "listrik",
        "selesai",
        "bunga",
        "mengikuti",
        "rubah",
        "bingkai",
        "gratis",
        "sering",
        "corong",
        "hijau",
        "gitar",
        "bahan makanan",
        "gelas",
        "hebat",
        "tertawa kecil",
        "potong rambut",
        "setengah",
        "buatan rumah",
        "terjadi",
        "madu",
        "terburu-buru",
        "seratus",
        "es",
        "rumah es",
        "berinvestasi",
        "mengundang",
        "ikon",
        "memperkenalkan",
        "lelucon",
        "riang",
        "jurnal",
        "melompat",
        "bergabung",
        "kanguru",
        "papan ketik",
        "dapur",
        "koala",
        "baik hati",
        "kaleidoskop",
        "pemandangan",
        "terlambat",
        "tertawa",
        "belajar",
        "lemon",
        "surat",
        "bunga lili",
        "majalah",
        "laut",
        "marshmallow",
        "labirin",
        "bermeditasi",
        "melodi",
        "menit",
        "monumen",
        "bulan",
        "sepeda motor",
        "gunung",
        "musik",
        "utara",
        "hidung",
        "malam",
        "nama",
        "tidak pernah",
        "bernegosiasi",
        "angka",
        "lawan",
        "gurita",
        "pohon ek",
        "pesanan",
        "terbuka",
        "kutub",
        "mengepak",
        "lukisan",
        "orang",
        "piknik",
        "bantal",
        "pizza",
        "podcast",
        "presentasi",
        "anak anjing",
        "puzzle",
        "resep",
        "melepaskan",
        "restoran",
        "berputar",
        "memutar balik",
        "ruangan",
        "berlari",
        "rahasia",
        "benih",
        "kapal",
        "kemeja",
        "harus",
        "kecil",
        "pesawat luar angkasa",
        "melihat bintang",
        "keterampilan",
        "jalan",
        "gaya",
        "matahari terbit",
        "taksi",
        "rapi",
        "pengatur waktu",
        "bersama",
        "gigi",
        "wisatawan",
        "perjalanan",
        "truk",
        "di bawah",
        "berguna",
        "unicorn",
        "unik",
        "meningkatkan",
        "seragam",
        "vas",
        "biola",
        "pengunjung",
        "visi",
        "volume",
        "pemandangan",
        "anjing laut",
        "mengembara",
        "dunia",
        "musim dingin",
        "baik",
        "angin puyuh",
        "sinar-X",
        "xylophone",
        "yoga",
        "yogurt",
        "yoyo",
        "kamu",
        "tahun",
        "lezat",
        "zebra",
        "zigzag",
        "zoologi",
        "zona",
        "semangat")
